export {Datatable, default as datatableReducer} from './datatable'
export {Image, default as imageReducer} from './image'
export {Report_table, default as report_tableReducer } from './report-table'
export {Tabset_page, default as tabset_pageReducer} from './tabset-page'
export {Tabset_profile, default as tabset_profileReducer} from './tabset-profile'