export {Datatable, default as datatableReducer} from './Datatable'
export {Image, default as imageReducer} from './Image'
export {Report_table, default as report_tableReducer } from './Report-table'
export {Tabset_page, default as tabset_pageReducer} from './Tabset-page'
export {Tabset_profile, default as tabset_profileReducer} from './Tabset-profile'