export {default as ForgetPassword} from './forget-password'
export {Login, default as loginReducer} from './login'
export {default as MyAccount} from './myAccount'
export {default as Profile} from './profile'
export {default as Register} from './register'