export {ForgetPassword} from './forget-password'
export {Login, default as loginReducer} from './login'
export {MyAccount} from './myAccount'
export {Register} from './register'
export {MyCarPage, default as myCarReducer} from './MyCar'