export {default as Recent} from './recent'
export {default as Comment} from './comment'
export {default as Media} from './media'
export {default as Popular} from './popular'
export {default as boardReducer} from './boardReducer'
export {default as BoardSearch} from './boardSearch'