export {default as Recent} from './Recent'
export {default as Comment} from './Comment'
export {default as Media} from './Media'
export {default as Popular} from './Popular'
export {default as RefreshInfo} from './refresh'
export {default as boardReducer} from './BoardReducer'