export {default as BoardMain} from './page/ClassicBoard.main'
export {default as BoardDetail} from './page/ClassicBoard.details'
export {default as BoardInput} from './page/PostInput'
export {default as BoardUpdate} from './page/PostUpdate'
export {default as PostItem} from './page/post-item'