export {Community, default as communityReducer} from './Community'
export {Dashboard, default as dashboardReducer } from './Dashboard'
export {ElecCar, default as elecCarReducer} from './ElecCar'
export {User, default as userReducer} from './User'
export {Notice, default as noticeReducer} from './Notice'
export {Orders, default as ordersReducer} from './Orders'
export {Tabset_user, default as tabset_userReducer} from './Tabset-user'
export {UsedCar, default as usedCarReducer} from './UsedCar'