export {Community, default as communityReducer} from './community'
export {Dashboard, default as dashboardReducer } from './dashboard'
export {ElecCar, default as elecCarReducer} from './elecCar'
export {User, default as userReducer} from './user'
export {Notice, default as noticeReducer} from './notice'
export {Orders, default as ordersReducer} from './orders'
export {Profile, default as profileReducer} from './profile'
export {Reports, default as reportsReducer} from './report'
export {Tabset_user, default as tabset_userReducer} from './tabset-user'
export {UsedCar, default as usedCarReducer} from './usedCar'